CommCare for ICT4D Teams
dimagi/dimagi.com pull request #296
Opened 2020-12-22 18:48 UTC by hemanthReddy06

- Added new page CommCare for ICT4D Teams
- Copy updates for  CommCare for M&E

2021-01-12 15:42 UTC, biyeun requested changes
just a couple code best practices requests with indentation changes but otherwise looking good. happy to merge when those are done

2021-01-12 15:42 UTC, biyeun commented on dimagi/pages/templates/sections/commcare/commcare_ict4d/tools.html
> +    	<div class="wistia-container">
indentation here needs to be fixed

2021-01-12 15:42 UTC, biyeun commented on dimagi/pages/templates/sections/commcare/commcare_ict4d/tools.html
> +	</div>
indentation here needs to be fixed, not clear on first glance what this div belongs to

2021-01-12 15:42 UTC, biyeun commented on dimagi/pages/templates/sections/commcare/commcare_ict4d/track_program.html
> +        {% blocktrans %}
indentation looks off

2021-01-12 16:40 UTC, hemanthReddy06 commented
@biyeun Updated with indentation changes.

2021-01-14 20:33 UTC, biyeun approved these changes

2021-01-14 20:33 UTC, merged