Fission/dhis2 toolkit update
dimagi/dimagi.com pull request #312
Opened 2021-03-19 10:22 UTC by hemanthReddy06

2021-03-26 17:25 UTC, biyeun commented
@hemanthReddy06  I fixed the issue with the CTA. Looks like the `<a>` tag wrapped around the `cta` did not work well because the `cta` creates another `<a>` tag and nested anchor tags are not valid HTML

2021-03-29 16:05 UTC, biyeun commented on dimagi/pages/templates/partials/hubspot_cta.html
> +      <!-- <img class="hs-cta-img"
i don't think this should be commented out

2021-03-29 16:06 UTC, biyeun requested changes
one small change that needs to be reverted with the commented-out image on the hubspot_cta template

2021-03-29 16:13 UTC, hemanthReddy06 commented
> one small change that needs to be reverted with the commented-out image on the hubspot_cta template

Updated.

2021-03-29 16:16 UTC, biyeun approved these changes

2021-03-29 16:17 UTC, biyeun commented
@hemanthReddy06 thank you! whoa that was quick... 👀  don't forget to enjoy the holiday and sleep too ^_^

2021-03-29 16:17 UTC, merged